<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bartz24.Memory\Bartz24.Memory.csproj" />
    <ProjectReference Include="..\RandoWPF\Bartz24.RandoWPF.csproj" />
  </ItemGroup>

</Project>
