using Bartz24.FF13_2_LR;

namespace Bartz24.LR;

public class DataStoreBtAbility : DataStoreWDBEntry
{
    public string sStringResId { get; set; }
    public string sInfoStResId { get; set; }
    public string sScriptId { get; set; }
    public string sAblArgStr0 { get; set; }
    public string sAblArgStr1 { get; set; }
    public string sAutoAblStEff0 { get; set; }
    public float fDistanceMin { get; set; }
    public float fDistanceMax { get; set; }
    public float fMaxJumpHeight { get; set; }
    public float fYDistanceMin { get; set; }
    public float fYDistanceMax { get; set; }
    public string sReplaceAirAttack { get; set; }
    public string sReplaceAirAir { get; set; }
    public string sReplaceFinish { get; set; }
    public string sReplaceEnAttr { get; set; }
    public string sActionId0 { get; set; }
    public string sActionId1 { get; set; }
    public string sActionId2 { get; set; }
    public string sActionId3 { get; set; }
    public string sRtDamSrc { get; set; }
    public string sRefDamSrc { get; set; }
    public string sSubRefDamSrc { get; set; }
    public string sSlamDamSrc { get; set; }
    public string sCamArtsSeqId0 { get; set; }
    public string sCamArtsSeqId1 { get; set; }
    public string sCamArtsSeqId2 { get; set; }
    public string sCamArtsSeqId3 { get; set; }
    public string sRedirectAbility0 { get; set; }
    public string sRedirectTo0 { get; set; }
    public string sRedirectAbility1 { get; set; }
    public string sRedirectTo1 { get; set; }
    public string sRedirectAbility2 { get; set; }
    public string sRedirectTo2 { get; set; }
    public string sRedirectAbility3 { get; set; }
    public string sRedirectTo3 { get; set; }
    public int u1ComAbility { get; set; }
    public int u1RsvFlag0 { get; set; }
    public int u1RsvFlag1 { get; set; }
    public int u1RsvFlag2 { get; set; }
    public int u1RsvFlag3 { get; set; }
    public int u1RsvFlag4 { get; set; }
    public int u1RsvFlag5 { get; set; }
    public int u1RsvFlag6 { get; set; }
    public int u1RsvFlag7 { get; set; }
    public int u1OvKill { get; set; }
    public int u4ArtsNameHideKd { get; set; }
    public int u14ArtsNameFrame { get; set; }
    public int u4MenuCategory { get; set; }
    public int u8AblSndKind { get; set; }
    public int i12MenuSortNo { get; set; }
    public int u4TargetListKind { get; set; }
    public int u8AbilityKind { get; set; }
    public int i16ScriptArg0 { get; set; }
    public int i16ScriptArg1 { get; set; }
    public int i16AblArgInt0 { get; set; }
    public int i16AblArgInt1 { get; set; }
    public int u4UpAblKind { get; set; }
    public int i17AtbCount { get; set; }
    public int u1AtbOverHeat { get; set; }
    public int u4Lv { get; set; }
    public int u4AblType { get; set; }
    public int u1NoDespel { get; set; }
    public int u1TgPain { get; set; }
    public int i12AtRnd { get; set; }
    public int i12AtbStayCount { get; set; }
    public int u1TgFoge { get; set; }
    public int u1NoBackStep { get; set; }
    public int u1AIWanderFlag { get; set; }
    public int u1AutoAblStEfEd0 { get; set; }
    public int u4YRgCheckType { get; set; }
    public int u16TechInputFrame { get; set; }
    public int u16TechInputPrm0 { get; set; }
    public int u10TechBonusRate { get; set; }
    public int i16KeepVal { get; set; }
    public int u4AtDistKind { get; set; }
    public int u1CheckAutoRpl { get; set; }
    public int u1SeqParts { get; set; }
    public int u14TgElemId { get; set; }
    public int u10OpProp0 { get; set; }
    public int u8ExecAngle { get; set; }
    public int i16AutoAblStEfTi0 { get; set; }
    public int u4JumpAttackType { get; set; }
    public int u4ReplaceFinishExecCt { get; set; }
    public int u1SeqTermination { get; set; }
    public int u5ActSelType { get; set; }
    public int u10ReplaceCtg1 { get; set; }
    public int u10ReplaceCtg2 { get; set; }
    public int u10ReplaceCtg3 { get; set; }
    public int u8ShortCutNo { get; set; }
    public int u4LoopFinCond { get; set; }
    public int u16LoopFinArg { get; set; }
    public int i16RefDamSrcRpt { get; set; }
    public int i16SubRefDamSrcRp { get; set; }
    public int u8CamArtsSelType { get; set; }
}
