using Bartz24.FF13_2_LR;

namespace Bartz24.FF13_2;

public class DataStoreBtCharaSpec : DataStoreWDBEntry
{
    public string sCharaSpec { get; set; }
    public string sBaseBtSpec { get; set; }
    public string sNameStrResID { get; set; }
    public string sNameStrRsv0 { get; set; }
    public string sWandIdNag { get; set; }
    public string sWandIdAg { get; set; }
    public float fAtkLen { get; set; }
    public string sScriptId { get; set; }
    public string sAiSheetName { get; set; }
    public string sAbility0 { get; set; }
    public string sAbility1 { get; set; }
    public string sAbility2 { get; set; }
    public string sAbility3 { get; set; }
    public string sAbility4 { get; set; }
    public string sAbility5 { get; set; }
    public string sAbility6 { get; set; }
    public string sAbility7 { get; set; }
    public string sAbility8 { get; set; }
    public string sAbility9 { get; set; }
    public string sAbility10 { get; set; }
    public string sAbility11 { get; set; }
    public string sAbility12 { get; set; }
    public string sAbility13 { get; set; }
    public string sAbility14 { get; set; }
    public string sAbility15 { get; set; }
    public float fFReserve0 { get; set; }
    public float fFReserve1 { get; set; }
    public float fFReserve2 { get; set; }
    public float fFReserve3 { get; set; }
    public string sEffId0 { get; set; }
    public int iEffArg0 { get; set; }
    public string sSndId0 { get; set; }
    public string sEffId1 { get; set; }
    public int iEffArg1 { get; set; }
    public string sSndId1 { get; set; }
    public string sPartCharSpec0 { get; set; }
    public string sPartCharSpec1 { get; set; }
    public string sPartCharSpec2 { get; set; }
    public string sPartCharSpec3 { get; set; }
    public string sPartCharSpec4 { get; set; }
    public string sPartCharSpec5 { get; set; }
    public string sPartCharSpec6 { get; set; }
    public string sPartCharSpec7 { get; set; }
    public string sMogClockId { get; set; }
    public int u6PcKind { get; set; }
    public int u6RoleStyle { get; set; }
    public int u8Rank { get; set; }
    public int u1NoHide { get; set; }
    public int u1FixPos { get; set; }
    public int u1FixFinArts { get; set; }
    public int u1NoRdrToPa { get; set; }
    public int u1NoHitBack { get; set; }
    public int u1FlagRsv0 { get; set; }
    public int u1FlagRsv1 { get; set; }
    public int u1FlagRsv2 { get; set; }
    public int u1FlagRsv3 { get; set; }
    public int u1FlagRsv4 { get; set; }
    public int u1FlagRsv5 { get; set; }
    public int u1FlagRsv6 { get; set; }
    public int u1FlagRsv7 { get; set; }
    public int u1FlagRsv8 { get; set; }
    public int u1FlagRsv9 { get; set; }
    public int u1FlagRsv10 { get; set; }
    public int u24MaxHp { get; set; }
    public int u1NoBlast { get; set; }
    public int u1NoSlam { get; set; }
    public int u1CamBigEnemy { get; set; }
    public int i1Reserve5 { get; set; }
    public int u12MaxAtb { get; set; }
    public int u16AgCount { get; set; }
    public int u4AiArg { get; set; }
    public int u16AgCountRnd { get; set; }
    public int u16AtbInit { get; set; }
    public int u16AtbInitRnd { get; set; }
    public int u16StatusStr { get; set; }
    public int u16StatusMgk { get; set; }
    public int u16StatusDef { get; set; }
    public int u16StatusMgDef { get; set; }
    public int i16StEfEndRecSpd { get; set; }
    public int i8StEfEndCoef { get; set; }
    public int u12KeepVal { get; set; }
    public int i8RegBlast { get; set; }
    public int u4Race { get; set; }
    public int i8RegBlastBr { get; set; }
    public int i8RegSlam { get; set; }
    public int i8RegSlamBr { get; set; }
    public int i8AiParam0 { get; set; }
    public int u12BrChainBonus { get; set; }
    public int u12MaxBp { get; set; }
    public int i8AiParam1 { get; set; }
    public int i16SynchroUpProp { get; set; }
    public int u8IdleRndCoef { get; set; }
    public int u4ElemDefEx0 { get; set; }
    public int u4ElemDefEx1 { get; set; }
    public int i16CamLimRotDeg { get; set; }
    public int u4ElemDefEx2 { get; set; }
    public int u4ElemDefEx3 { get; set; }
    public int u4ElemDefEx4 { get; set; }
    public int u4ElemDefEx5 { get; set; }
    public int u4ElemDefEx6 { get; set; }
    public int u4ElemDefEx7 { get; set; }
    public int u8StatusDef0 { get; set; }
    public int u8StatusDef1 { get; set; }
    public int u8StatusDef2 { get; set; }
    public int u8StatusDef3 { get; set; }
    public int u8StatusDef4 { get; set; }
    public int u8StatusDef5 { get; set; }
    public int u8StatusDef6 { get; set; }
    public int u8StatusDef7 { get; set; }
    public int u8StatusDef8 { get; set; }
    public int u8StatusDef9 { get; set; }
    public int u8StatusDef10 { get; set; }
    public int u8StatusDef11 { get; set; }
    public int u8StatusDef12 { get; set; }
    public int u8StatusDef13 { get; set; }
    public int u8StatusDef14 { get; set; }
    public int u8StatusDef15 { get; set; }
    public int u8StatusDef16 { get; set; }
    public int u8StatusDef17 { get; set; }
    public int u8StatusDef18 { get; set; }
    public int u8StatusDef19 { get; set; }
    public int u8StatusDef20 { get; set; }
    public int u8StatusDef21 { get; set; }
    public int u8StatusDef22 { get; set; }
    public int u8StatusDef23 { get; set; }
    public int u8StatusDef24 { get; set; }
    public int u8StatusDef25 { get; set; }
    public int u8StatusDef26 { get; set; }
    public int u8StatusDef27 { get; set; }
    public int u8StatusDef28 { get; set; }
    public int u8StatusDef29 { get; set; }
    public int u8StatusDef30 { get; set; }
    public int u8StatusDef31 { get; set; }
    public int u10Prop0 { get; set; }
    public int u10Prop1 { get; set; }
    public int u4PartCharKind { get; set; }
    public int u10Prop2 { get; set; }
    public int u10Prop3 { get; set; }
    public int u10Prop4 { get; set; }
    public int u1NoInitPart { get; set; }
    public int i16Reserve0 { get; set; }
    public int i16Reserve1 { get; set; }
    public int i16Reserve2 { get; set; }
    public int u12Reserve3 { get; set; }
    public int u6Reserve4 { get; set; }
    public int u14NameElemId { get; set; }
    public string s10DropItem0 { get; set; }
    public int u14ElemIdRsv0 { get; set; }
    public int u14ElemIdRsv1 { get; set; }
    public int u14EffPos0 { get; set; }
    public int u14EffPos1 { get; set; }
    public int u14TgElemId0 { get; set; }
    public int u8NumDrop0 { get; set; }
    public string s10DropItem1 { get; set; }
    public int u24AbilityPoint { get; set; }
    public int u8NumDrop1 { get; set; }
    public int u14DropProb0 { get; set; }
    public int u14DropProb1 { get; set; }
    public string s10DropItem2 { get; set; }
    public int u8NumDrop2 { get; set; }
    public int u14DropProb2 { get; set; }
    public int u16DropGil { get; set; }
    public int u16ResultTime { get; set; }
}
